### PR TITLE
New UI design

### PR DESCRIPTION
**Pull request by IrynaSpyrydonova**
Closes gh-9

### CODE REVIEW

**Review by fmkarakus — APPROVED** [review]
Well Done, Iryna! Looks very nice.
After we add delete property, we will need to update `id: courses.length + 1` part in controllers.js file, not to have duplicate id's.

**Comment by IrynaSpyrydonova** [comment]
@fmkarakus  oh, I am sorry, totally forgot about that, give me a bit of time, I will push changes

**Comment by IrynaSpyrydonova** [comment]
@fmkarakus  I am sorry for waisting your time, that you have to check one more time (( but I added nextId, changed a bit scrolling for open details and added toggle for Details button, since my css was a bit complicated and for Razvan could be quite confusing. Thank you

**Comment by fmkarakus** [comment]
@IrynaSpyrydonova . No problem, this is not waste of time. You have done a lot of work again.
I still thing ID will be a problem. Every time page is loaded, `nextId`  will be reset to 13, since it is in `init.js`, am i wrong?
The solution can be keeping nextID in the back-end or I would simply make a loop to find the highest existing Id, then add 1. What do you think?

**Comment by IrynaSpyrydonova** [comment]
@fmkarakus  yes, you are right , I will do the same way, like we had for last Sunday project

**Comment by IrynaSpyrydonova** [comment]
@fmkarakus , done 🙂

**Review by murvanessa — COMMENTED** [review]
for me is ok this way

**Pull request merged**
